const PORT = 5000;

const TEMPLATES_FOLDER = "./templates";
const RENDERED_TEMPLATES_FOLDER = "./rendered_templates";

const STATIC_FOLDER = "static";
const STATIC_VIRTUAL_PATH = "/static";

const HTML_FILES_TO_IGNORE = ["base.html"];
const SELECT_LANGUAGE_PAGE = "select_language.html";

const LANGUAGE_ABBREVIATIONS = ["en", "de"];

export { PORT, TEMPLATES_FOLDER, HTML_FILES_TO_IGNORE, SELECT_LANGUAGE_PAGE, LANGUAGE_ABBREVIATIONS, RENDERED_TEMPLATES_FOLDER, STATIC_FOLDER, STATIC_VIRTUAL_PATH };